services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin 
      MINIO_ROOT_PASSWORD: adminadmin  
    volumes:
      - minio_data:/data 
    ports:
      - "9000:9000"  
      - "9001:9001"  
    restart: unless-stopped

volumes:
  minio_data: 
